# Generated by Django 4.0.4 on 2023-01-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_rename_title_entry_entry_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='entry_title',
            new_name='entry_head',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='list_title',
            new_name='list_head',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='video_head',
        ),
    ]
