# Generated by Django 4.0.4 on 2023-01-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_alter_entry_image_alter_entry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images', verbose_name='Image'),
        ),
    ]
