# Generated by Django 4.0.4 on 2023-01-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_alter_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images', verbose_name='Image'),
        ),
    ]
