# Generated by Django 4.1.5 on 2023-02-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0010_remove_video_thumbnail_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
    ]
