# Generated by Django 4.1.5 on 2023-02-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0011_remove_video_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='video',
        ),
    ]
